name: task_management3
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  ionicons: 0.2.1
  cool_alert: ^1.1.0
  firebase_core: 2.4.1
  firebase_auth: 4.2.5
  google_sign_in: 5.4.3
  cloud_firestore: 4.3.1
  flutter: 
    sdk: flutter
  image_picker: ^0.8.6+1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/profil.jpg
  uses-material-design: true

