// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs94wuseysFJBUpC3G6K0innWb62c_T48',
    appId: '1:781943895013:web:7cad5660598bd84437750c',
    messagingSenderId: '781943895013',
    projectId: 'task-management-5692d',
    authDomain: 'task-management-5692d.firebaseapp.com',
    storageBucket: 'task-management-5692d.appspot.com',
    measurementId: 'G-S70EZ8JF56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHI2ugsxumumQcbtHlX8AvfNdnu89C6Us',
    appId: '1:781943895013:android:0d39422f52008b4737750c',
    messagingSenderId: '781943895013',
    projectId: 'task-management-5692d',
    storageBucket: 'task-management-5692d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE-5Mk5fM9HDEAgzxCGfL5-_CRhFCLQfw',
    appId: '1:781943895013:ios:c6a2aa109056ee0a37750c',
    messagingSenderId: '781943895013',
    projectId: 'task-management-5692d',
    storageBucket: 'task-management-5692d.appspot.com',
    androidClientId: '781943895013-s08jr433friidgnece6kclca70cv21n0.apps.googleusercontent.com',
    iosClientId: '781943895013-m3coeq0b1tdko7duhvb29naihnn14j7r.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagement3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE-5Mk5fM9HDEAgzxCGfL5-_CRhFCLQfw',
    appId: '1:781943895013:ios:c6a2aa109056ee0a37750c',
    messagingSenderId: '781943895013',
    projectId: 'task-management-5692d',
    storageBucket: 'task-management-5692d.appspot.com',
    androidClientId: '781943895013-s08jr433friidgnece6kclca70cv21n0.apps.googleusercontent.com',
    iosClientId: '781943895013-m3coeq0b1tdko7duhvb29naihnn14j7r.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagement3',
  );
}
